services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=taskmanagerdb'
      - 'POSTGRES_PASSWORD=123456'
      - 'POSTGRES_USER=apptask'
    ports:
      - '5432:5432'
